### ISSUE TITLE
Inside Job vs Tollbooth / interesting corp play /  offline-images

### ISSUE THREAD

**Issue by olompumpa** [bobtheuberfish/chiriboga#117]
1.
Inside Job doesnt work against tollbooth
https://netrunnerdb.com/en/card/01021

2.
The Corp was playing weird, not playing/scoring agendas.  

3.
Images are not displayed when I want to play offline.
https://github.com/bobtheuberfish/chiriboga/wiki/Running-locally

/ THX for your work.
[chiriboga-log-2023-02-06T20 44 53.364Z.txt](https://github.com/bobtheuberfish/chiriboga/files/10669064/chiriboga-log-2023-02-06T20.44.53.364Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for reporting this. I am busy with other projects at the moment but I hope to investigate these before the end of Feb.

**Comment by bobtheuberfish** [comment]
Have you played it offline before with images showing or is this the first time you've tried? Just to make sure, today I followed the instructions on the "Running locally" page and the images worked for me.
Did you make sure to replace the images folder from the chiriboga source with the images folder from the images_sg_and_su21 file?

**Comment by olompumpa** [comment]
I must have missed something, sorry, my bad - the offline really works.
(except for the pictures on the home page, but they are not important at all) 
![miss](https://user-images.githubusercontent.com/11477707/219087526-fc14bb7f-475e-4d8f-8aad-ec3c04a18209.jpg)

**Comment by bobtheuberfish** [comment]
It seems that you have an outdated version of the images folder. Here are the four missing files, put these in your images folder. 

![menu_runner_4_sg_su21](https://user-images.githubusercontent.com/87321962/219163325-8ed5f19c-22f7-4a68-877d-490001544691.png)
![menu_corp_3_sg](https://user-images.githubusercontent.com/87321962/219163350-02b5995f-e78d-486e-8b2c-68773c8ec9aa.png)
![menu_corp_4_sg_su21](https://user-images.githubusercontent.com/87321962/219163362-24d1255b-8426-42be-8f93-e34d18b1497a.png)
![menu_runner_3_sg](https://user-images.githubusercontent.com/87321962/219163372-769338d6-d6c2-40bb-844d-ecdb2fc7dc1f.png)

I will get back to you about the other two issues later.

**Comment by bobtheuberfish** [comment]
Oh github has renamed them. They should be:
menu_runner_4_sg_su21.png
menu_corp_3_sg.png
menu_corp_4_sg_su21.png
menu_runner_3_sg.png

**Comment by bobtheuberfish** [comment]
I have fixed the Inside Job with Tollbooth issue but am just testing some potential related issues before I upload it.
I have read the log for the Corp not playing/scoring agendas. It seems they were not drawing much ice so couldn't build a strong scoring server. Also, because of the pressure you were putting on R&D, they put a lot of their ice there instead of on the remote. I think if they had drawn more ice they could have done better in this situation but were just having a bit of bad luck in that area. Feel free to suggest any specific hints that you think I could give the Corp AI, especially if you see this happening a lot.
