### ISSUE TITLE
Docklands Pass+Jailbreak

### ISSUE THREAD

**Issue by olompumpa** [bobtheuberfish/chiriboga#129]
The Docklands Pass was installed, then I started my run with a Jailbreak. As far as I know, I should have accessed  1+2 = 3 cards, but I only got two.

thanks in advance
[chiriboga-log-2023-03-25T14 06 56.534Z.txt](https://github.com/bobtheuberfish/chiriboga/files/11069090/chiriboga-log-2023-03-25T14.06.56.534Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for reporting this bug and for including the log. I am amazed this bug has not been previously reported - it looks like I implemented Docklands Pass wrong right when I first made it (it requires that no runs have ended this turn, rather than checking if this is the first time HQ has been breached). I can't fix this bug right away because I will need to make some changes to the breaching code and then do testing to make sure I don't break anything. I should be able to fix this within the next week or so.
