### ISSUE TITLE
Can't use Chameleon on Ansel 1.0 using Kit

### ISSUE THREAD

**Issue by Kwaice** [bobtheuberfish/chiriboga#78]
Running a server protected by Ansel. Somehow can't use Chameleon on the ice.

![image](https://user-images.githubusercontent.com/25953788/169806251-70f0bb03-cbf0-4050-81fa-f5f4c5928723.png)

**Comment by bobtheuberfish** [comment]
Thank you for this report, and for including a screenshot.
From what I can see, Chameleon should not be able to interface with Ansel 1.0 because it does not have sufficient strength (Chameleon only has 3 strength, Ansel 1.0 has 4 strength).
If my understanding is correct then this is correct implementation?

**Comment by Kwaice** [comment]
I could not increase chameleon strength either while having enough credits to break too.

I'll try to reproduce the issue.

**Comment by Kwaice** [comment]
I didn't notice that you can't increase its strength haha.

Sorry, closing :)
