### ISSUE TITLE
Spin doctor error 

### ISSUE THREAD

**Issue by R41B** [bobtheuberfish/chiriboga#91]
Hi there, 
I’m still enjoying your project almost daily! One thing I noticed: when installing Spin Doctor last click, it automatically ends your turn, before I can rez and use it. I think this is not how it should work, right? 
thanks in advance!

**Comment by bobtheuberfish** [comment]
Hi, thanks for this report! Glad to hear you're still enjoying it.

You're right that it is not behaving correctly. This is actually a feature behaving like a bug. Basically part of the design of Chiriboga is to reduce the times when you are given opportunities to act, only pausing the game for choices when relevant. For example, according the the rules, you can increase an icebreaker's strength during any paid ability window, even though it's usually pointless. In Chiriboga, you can only increase the strength of an icebreaker during an encounter.

The hard part for me is predicting all the times when you would want to use something, without having the game ask you to continue all the time. This is an open problem at the moment, and I'm looking for ideas. One of the ways I intend to improve this (in an update later this year) is that if the game is paused for any choice, all legal options would be available to use, even if they normally wouldn't be sensible to do. This will mean I don't have to predict every possible interaction. I am also thinking of adding a visible timer that automatically continues after a few seconds if you don't want to take any action, so you don't have to click Continue all the time.

Regarding Spin Doctor specifically: why would you would want to rez and use a Spin Doctor after your last click? I can understand why you would use it before your last click, because you might draw something useful. But after your last click you won't be able to use any cards that you draw. If it's to have more cards in HQ to make accesses more random, you might as well rez it on the next approach to HQ. Similar logic applies if you want to interact with R&D or Archives. Chiriboga will allow you to use it during these scenarios (as well as the approach to the server in which Spin Doctor is installed).

**Comment by R41B** [comment]
Ah right, I understand your design decision.Thanks for the elaborate reply! I have to say: every time I have a Spin Doctor on the table, I use it much faster than I would do in real life, because I'm "annoyed" by all the pop-ups it gives at every action window. So I see what you are struggling with here... I don't know anything about programming, so I really can't help you out. The option with the times sounds interesting, but I can imagine that it slows down the speed of the game a lot...

To answer your question: When would I like to use spin doctor last click. This case happens when I'm "agenda flooded". I want to draw up with Spin Doctor last click, to be able to have my hand size above the hand size limit, so I can use the discard phase to discard my agenda's, and have Spin Doctor on the table to be able to shuffle them back into the deck.

Another totally different thing I notice when I use Chiriboga: My computer/phone get really heated and it drains my battery. Any idea why this is so heavy for my four years old iPhone/MacBook Air?

**Comment by bobtheuberfish** [comment]
Thank you for the information about using Spin Doctor last click. I'll keep thinking about this general challenge over the next few months as work through the last few cards in System Update 2021.

At the moment I could only guess at why Chiriboga is soaking so much power. It might be the graphics engine, sometimes mobile devices struggle with rendering lots of transparent objects. There are possibly some optimisations I could do. I'm not satisfied with the framerate on my old laptop either, so I'll have a think about this and maybe do some analysis at some point.

**Comment by bobtheuberfish** [comment]
Can now rez and trigger Spin Doctor during Corp EOT but sorry I couldn't fix the overheating. I've also implemented an 'auto-skip' option that appears when there are a lot of pop-ups.
